apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clickhouse-credentials-external-secret
  namespace: {{ .Env.CLICKHOUSE_NAMESPACE }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: clickhouse-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        admin: "{{ `{{ .admin }}` }}"
  data:
    - secretKey: admin
      remoteRef:
        key: clickhouse/credentials
        property: admin