apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: clickhouse
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
  configuration:
    clusters:
      - name: default
        layout:
          shardsCount: 1
          replicasCount: 1
    zookeeper:
      nodes:
        - host: zookeeper
          port: 2181
    users:
      admin/k8s_secret_password: clickhouse-credentials/admin
      admin/networks/ip: "::/0"
      admin/access_management: 1
      # Disable default user
      default/password: "disabled"
      default/networks/ip: "127.0.0.1"
    profiles:
      default/max_memory_usage: {{ .Env.CLICKHOUSE_MAX_MEMORY_USAGE }}
      default/max_bytes_before_external_group_by: {{ .Env.CLICKHOUSE_MAX_BYTES_BEFORE_EXTERNAL_GROUP_BY }}
      default/max_bytes_before_external_sort: {{ .Env.CLICKHOUSE_MAX_BYTES_BEFORE_EXTERNAL_SORT }}
      default/add_http_cors_header: 1
  templates:
    volumeClaimTemplates:
      - name: data-volume-template
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
      - name: log-volume-template
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
