apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hf-token-external-secret
  namespace: {{ .Env.VLLM_NAMESPACE }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: hf-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: vllm/huggingface
        property: token
