apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: encryption-key-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: encryption-key
    creationPolicy: Owner
  data:
  - secretKey: key
    remoteRef:
      key: langfuse/encryption-key
      property: value
