apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-auth-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: minio-auth
    creationPolicy: Owner
  data:
  - secretKey: access_key
    remoteRef:
      key: langfuse/minio
      property: access_key
  - secretKey: secret_key
    remoteRef:
      key: langfuse/minio
      property: secret_key
