apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-auth-external-secret
  namespace: {{ .Env.LANGFUSE_NAMESPACE }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: postgres-auth
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: langfuse/postgres
      property: username
  - secretKey: password
    remoteRef:
      key: langfuse/postgres
      property: password
  - secretKey: url
    remoteRef:
      key: langfuse/postgres
      property: url
