apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-auth-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: redis-auth
    creationPolicy: Owner
  data:
  - secretKey: secret
    remoteRef:
      key: langfuse/redis
      property: secret
