apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-auth-external-secret
  namespace: {{ .Env.LANGFUSE_NAMESPACE }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: s3-auth
    creationPolicy: Owner
  data:
  - secretKey: access_key
    remoteRef:
{{- if eq .Env.LANGFUSE_OBJECT_STORAGE "rustfs" }}
      key: langfuse/rustfs
{{- else }}
      key: langfuse/minio
{{- end }}
      property: access_key
  - secretKey: secret_key
    remoteRef:
{{- if eq .Env.LANGFUSE_OBJECT_STORAGE "rustfs" }}
      key: langfuse/rustfs
{{- else }}
      key: langfuse/minio
{{- end }}
      property: secret_key
