# Default values for ch-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/caioricciuti/ch-ui
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 5521

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ch-ui.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  timeoutSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

# CH-UI specific configuration
clickhouse:
  # ClickHouse server URL
  url: "http://clickhouse:8123"

  # Authentication configuration
  auth:
    # ClickHouse username
    username: "default"
    # ClickHouse password (ignored if existingSecret is set)
    password: ""
    # Name of an existing secret containing the authentication credentials
    existingSecret: ""
    # Secret keys for authentication credentials
    secretKeys:
      # Key in the secret containing the password
      password: "clickhouse-password"

  # Advanced configuration
  useAdvanced: false
  requestTimeout: 30000
  basePath: "/"

# Additional environment variables
extraEnvVars: []
# - name: MY_ENV_VAR
#   value: my-value

# Environment variables from existing ConfigMaps or Secrets
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
