apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airbyte-storage-pvc
  namespace: {{ .Env.AIRBYTE_NAMESPACE }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- $sc := getenv "STORAGE_CLASS" "" }}
  {{- if $sc }}
  storageClassName: {{ $sc }}
  {{- end }}
  resources:
    requests:
      storage: 10Gi
