apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airbyte-oauth-external-secret
  namespace: {{ .Env.AIRBYTE_NAMESPACE }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: airbyte-oauth-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        client_id: "{{ `{{ .client_id }}` }}"
  data:
    - secretKey: client_id
      remoteRef:
        key: airbyte/oauth
        property: client_id