apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dagster-database-external-secret
  namespace: {{ .Env.DAGSTER_NAMESPACE }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: dagster-database-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: dagster/database
        property: username
    - secretKey: password
      remoteRef:
        key: dagster/database
        property: password
    - secretKey: postgresql-password
      remoteRef:
        key: dagster/database
        property: password