apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-credentials
  namespace: {{ .Env.KEYCLOAK_NAMESPACE }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: keycloak/admin
        property: username
    - secretKey: password
      remoteRef:
        key: keycloak/admin
        property: password