apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: querybook-secret
  namespace: {{ .Env.QUERYBOOK_NAMESPACE }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: querybook-secret
    creationPolicy: Owner
  data:
    - secretKey: FLASK_SECRET_KEY
      remoteRef:
        key: querybook/config
        property: FLASK_SECRET_KEY
    - secretKey: DATABASE_CONN
      remoteRef:
        key: querybook/config
        property: DATABASE_CONN
    - secretKey: REDIS_URL
      remoteRef:
        key: querybook/config
        property: REDIS_URL
    - secretKey: ELASTICSEARCH_HOST
      remoteRef:
        key: querybook/config
        property: ELASTICSEARCH_HOST
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: querybook/config
        property: OAUTH_CLIENT_SECRET
