set fallback := true

[private]
default:
    @just --list --unsorted --list-submodules

mod airbyte 'airbyte/justfile'
mod cube 'cube/justfile'
mod bytebase 'bytebase/justfile'
mod longhorn 'longhorn/justfile'
