apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: superset-secret
    namespace: {{ .Env.SUPERSET_NAMESPACE }}
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: vault-secret-store
        kind: ClusterSecretStore
    target:
        name: superset-secret
        creationPolicy: Owner
    data:
        - secretKey: SECRET_KEY
          remoteRef:
              key: superset/config
              property: SECRET_KEY
        - secretKey: SQLALCHEMY_DATABASE_URI
          remoteRef:
              key: superset/config
              property: SQLALCHEMY_DATABASE_URI
        - secretKey: OAUTH_CLIENT_SECRET
          remoteRef:
              key: superset/config
              property: OAUTH_CLIENT_SECRET
