apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: kserve-s3-external-secret
    namespace: {{ .Env.KSERVE_NAMESPACE }}
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: vault-secret-store
        kind: ClusterSecretStore
    target:
        name: kserve-s3-credentials
        creationPolicy: Owner
        template:
            type: Opaque
            metadata:
                annotations:
                    serving.kserve.io/s3-endpoint: "minio.{{ .Env.MINIO_NAMESPACE }}.svc.cluster.local:9000"
                    serving.kserve.io/s3-usehttps: "0"
                    serving.kserve.io/s3-region: "us-east-1"
                    serving.kserve.io/s3-useanoncredential: "false"
            data:
                AWS_ACCESS_KEY_ID: "{{ `{{ .accesskey }}` }}"
                AWS_SECRET_ACCESS_KEY: "{{ `{{ .secretkey }}` }}"
    data:
        - secretKey: accesskey
          remoteRef:
              key: minio/admin
              property: username
        - secretKey: secretkey
          remoteRef:
              key: minio/admin
              property: password
