---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-db-external-secret
  namespace: {{ .Env.MLFLOW_NAMESPACE }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: mlflow-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: mlflow/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: mlflow/postgres
        property: password
