apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio
  namespace: {{ .Env.MINIO_NAMESPACE }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: minio
    creationPolicy: Owner
  data:
    - secretKey: rootUser
      remoteRef:
        key: minio/admin
        property: username
    - secretKey: rootPassword
      remoteRef:
        key: minio/admin
        property: password