apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-oidc
  namespace: {{ .Env.MINIO_NAMESPACE }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: minio-oidc
    creationPolicy: Owner
  data:
    - secretKey: clientId
      remoteRef:
        key: minio/oidc
        property: client_id
    - secretKey: clientSecret
      remoteRef:
        key: minio/oidc
        property: client_secret
