apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-operator
  namespace: {{ .Env.REDIS_OPERATOR_NAMESPACE }}
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      name: redis-operator
  namespaceSelector:
    matchNames:
      - {{ .Env.REDIS_OPERATOR_NAMESPACE }}
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
