apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-cluster-superuser
  namespace: {{ .Env.CNPG_NAMESPACE }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: postgres-cluster-superuser
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: postgres/admin
        property: username
    - secretKey: password
      remoteRef:
        key: postgres/admin
        property: password