apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-oidc
  namespace: {{ .Env.CODER_NAMESPACE }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: coder-oidc
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: coder/oidc
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: coder/oidc
        property: client_secret
