apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: temporal-web-auth
  namespace: {{ .Env.TEMPORAL_NAMESPACE }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: temporal-web-auth
    creationPolicy: Owner
  data:
  - secretKey: TEMPORAL_AUTH_CLIENT_ID
    remoteRef:
      key: keycloak/client/temporal
      property: client_id
  - secretKey: TEMPORAL_AUTH_CLIENT_SECRET
    remoteRef:
      key: keycloak/client/temporal
      property: client_secret
